### ISSUE TITLE
Fischer panda bug per v2.90?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1053]
https://community.victronenergy.com/questions/195728/fischer-panda-an-cerbo.html

(@martinbosma , lets discuss prio before you start on this)

**Comment by martinbosma** [comment]
This has been resolved in VenusOS v3.11, verified with customer on community.

There is however, another small issue that the customer can no longer control the Fischer Panda through modbus.
This is likely because since VenusOS v2.90, the generator start/stop service must be used to start/stop the Fischer Panda, even though the auto start/stop mode is not active. This must be properly documented on the wiki and perhaps the modbustcp documentation.
