### ISSUE TITLE
v3.00~37 generator icon missing from the Generator Overview page.

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1070]
![49995D44-000C-4BF9-B6D8-15B8E4364383](https://user-images.githubusercontent.com/5200296/236607569-41ca71e0-b8b2-427c-9ca1-c18c0e84cded.jpeg)

https://community.victronenergy.com/questions/202458/venus-os-v30037-available-for-beta-testing.html

**Comment by jepefe** [comment]
Issue introduced in this commit: https://github.com/victronenergy/gui/commit/9fdd8e0cdedb624627886399669f2f004dbf9804

That commit makes all the MbIcons using "source" property have a size of 0. There are other than the generator icon affected by this. 

Fixed in this branch: https://github.com/victronenergy/gui/commits/fix_icons
Fix added to the ToDo.
