### ISSUE TITLE
No Wi-Fi adapter connected Rapsberry Pi Zero 2w

### ISSUE THREAD

**Issue by ksherwood02** [victronenergy/venus#1120]
I've tried 2.90, 2.94, and 3.00, and none detect the wifi adapter.  Connmanctl shows bluetooth available and enabled, but I can't see the device with the VictronConnect app.

/proc/cpuinfo reports BCM2835, revision 902120, model Raspberry Pi Zero 2w Rev 1.0

![image](https://github.com/victronenergy/venus/assets/71787151/a12c1f19-8ece-4e7a-b5fd-82129af73949)

Thanks,
Kevin

**Comment by nmbath** [comment]
Please ask these sort of questions on the community forum at community.victronenergy.com.

This is a known issue and a search of the four will give you guidance on how to fix. The other alternative is to load the beta release of 3.10, which has fixes since beta release 3.10~4. Details of beta are on the community forum, a quick search will show details.
