### ISSUE TITLE
OS 3.10 large: SignalK not available & port 3000 not responding 

### ISSUE THREAD

**Issue by x7y8z9** [victronenergy/venus#1143]
on CerboGX.
Went back to 3.01, everything is working well again.

**Comment by mpvader** [comment]
Hi!

on a fresh install it works fine, and many systems that upgraded from a running v3.01 to v3.10 had no problems either.

Another user had a similar issue, and his data partition was full.

For solutions see here:
https://www.victronenergy.com/live/venus-os:large#disk_space_issues_data_partition_full

If you figure it out, please do let me know what the issue was.

and in case you can’t I recommend to either go to SignalK Slack for more help, or to our Modifications channel on Community.

I’ll close this issue now
