### ISSUE TITLE
Does this work on old MultiPlus Compact?

### ISSUE THREAD

**Issue by bbuster2** [victronenergy/venus#1174]
My RV has a Multiplus Compact with firmware version 142 at the end. 

Will this installed on a raspberry pi 4b work with this?

Also adding a display for the gui?
Sorry if this question should not be here but i couldn’t find any info on how to connect the raspberry to the multiplus. 

What and how do i need to connect the raspberry to make all work in an RV

**Comment by kwindrem** [comment]
This area is for internal Victron issue tracking only.

Questions such as this should be posted tothe Victron Community :

https://community.victronenergy.com

Since this is about a RPI, it should go in the Modications section.

But to answer your question:

I have a Multi Compact currently running v506 firmware. It connects fine to my Cerbo GX and also connected to my RPI4 running Venus OS. You will probably want to upgrade to a more recent version if you can. v142 is pretty old. Look in

https://professional.victronenergy.com

For an upgrade path.

Others should be able to help with the firmware upgrade if you post to the Victron forum.

You need the MK3 USB adapter to connect the Multi Compact to the RPI. It will also be necessary to upgrade the Multi's firmware.

If you have any VE.Direct devices (shunts, MPPTs), etc, you'll need a VE.Direct to USB adapter for each one.

The "official 7" Raspberry PI touchscreen" works well with Venus OS. I also used a Waveshare HDMI touchscreen that works with Venus OS:

https://www.amazon.com/gp/product/B077PLVZCX/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

You should look into my RpiDisplaySetup package that should make setting up the RPI touchscreen or an external HDMI touchscreen easier:

https://github.com/kwindrem/RpiDisplaySetup
