### ISSUE TITLE
Connecting other (type of) sensors to the Cerbo using the USB-RS485 cable

### ISSUE THREAD

**Issue by espenairmine** [victronenergy/venus#1268]
We have several installations where we are looking to use the Cerbo to measure other parameters, in this scenario, a depth sensor for a well. In theory the depth sensor is not very different than a tank sensor (though not using the same protocol)
Can we connect the depth sensor (a GLT500 from Gamicos, - https://www.gamicos.com/Products/GLT500-Pressure-Level-Sensor, running rs485, ) to the Cerbo using the USB to RS485 cable (https://www.victronenergy.com/accessories/rs485-to-usb-interface)?

**Comment by mpvader** [comment]
Hi Espen, 

Just the read out of such sensor onto the internal databus on the GX is something that can be done due to the openness of Venus OS, see how to make a driver on the wiki for that.

But to have it shown as depth, with proper unit and such requires work from us on all UIs to create the profile for such data. Which is hard to do by yourself even if you have software development capabilities or can hire them. We might do that at some point, but at the moment its not a prio.

If this is a large project, then please get in touch via the commercial route (distributor -> sales manager -> me) to see if we can prioritise it.

Thanks, Matthijs
