### ISSUE TITLE
gridless octo: test VE.Can port

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#192]
the second canbus port has been tested by Unipoin. But the VE.Can port has not been tested by Unipoin.

**Comment by mkrenzke** [comment]
Testing device received. We will test today.

**Comment by mkrenzke** [comment]
VE.Can successfully tested on both CAN Bus ports (VE.Can and regular CAN-Bus).

Communication works fine:

![image](https://user-images.githubusercontent.com/31248358/30804933-95601764-a1ef-11e7-9d45-c4ce57b7ebcd.png)

Two devices have been recognized (one per port). One appears disconnected since we switched the testing device to the other port. Which is exactly the behavior expected.
