### ISSUE TITLE
gridless octo: wifi networks show up twice

### ISSUE THREAD

**Issue by mkrenzke** [victronenergy/venus#197]
In the list of wifi networks each network appears twice. This does not seem to be a gui issue but a more general one. Because if we list networks in `connman` it appears to be the same.

In addition I was not able to test the access point function. What should be the SSID send out when AP is enabled? There was no network coming up when activating the access point.

I guess both effects do have a similar reason. Possibly the driver for RTL8723BU is not configured properly. Even if we are able to connect (as client) to a wifi and communicate through it successfully. And yes - with good results in signal strength.

**Comment by mpvader** [comment]
The issue is that the rtl is at a different position than expected.

See here to find out where to fix this for your test Octo:
https://github.com/victronenergy/meta-victronenergy/blob/master/meta-venus/recipes-core/udev/files/beaglebone/wlan-rename

@mansr is already making a change to make the scripts work for both the octo and the Venus GX

**Comment by mkrenzke** [comment]
Indeed changing udev rules worked do get wifi0 and ap0 device.

But no new network appearing... :-(

**Comment by mkrenzke** [comment]
Good news. It works!

There were two files missing:
```
/data/venus/wpa-psk
/data/venus/serial-number
```

When and how will they be set? While installation? Or first boot?

**Comment by mpvader** [comment]
> When and how will they be set?

In the manufacturing process. By our test equipment, see #185

**Comment by mkrenzke** [comment]
Okay. Thank you!
