### ISSUE TITLE
dbus-modbustcp improvements

### ISSUE THREAD

**Issue by edevries-victron** [victronenergy/venus#216]
### Status (updated 2019-6-22 by Matthijs)

- there is a branch in modbustcp, [WIP_qitems_and_diagnostics_service](https://github.com/victronenergy/dbus_modbustcp/tree/WIP_qitems_and_diagnostics_service). Waiting for inclusion. I does not apply cleanly.
- there is a branch in the gui, [feature/add-modbustcp-diagnosticspage](https://github.com/victronenergy/gui/tree/feature/add-modbustcp-diagnostics-page), waiting for inclusion. I rebased it on master today; and it applied cleanly.

### Initial text by Ernst
Some dbus-modbustcp improvements I have been working on in the past year, which have not been released yet:
* Update source to use VeQItems: this brings this module more in line with other C++ services, and improves performance. Now, only the D-Bus objects related to registers that are actively requested are monitored for changes instead of all D-Bus objects the could be requested. This improved performance on a typical system from approximately 4% to 1% CPU use.
* Publish a D-Bus (com.victronenergy.modbus) service which supplies the unit ID for each D-Bus service. Many customer questions about modbus TCP come down to misunderstanding how unit ID's are tied to D-Bus services. The service also publishes the last error (if any).  There is also a gui counterpart: it works, but does not look really good.
* Add write support for 32-bit integers
* Added unit tests (mostly to test data conversion D-Bus <-> modbus)
* Added a simple state engine to parse incoming modbus requests. In the original code, it was assumed that a read request from a TCP socket would always return a single and complete modbus request. This not guaranteed however. Whenever the assumption fails, the service will not respond to the message being send. Usually the origin code works well, but there have been a few reports of systems where the CCGX stopped responding to requests.

The branches involved are:
* dbus-modbustcp: [WIP_qitems_and_diagnostics_service](https://github.com/victronenergy/dbus_modbustcp/tree/WIP_qitems_and_diagnostics_service)

**Comment by 3dGrabber** [comment]
#### gui - WIP_modbustcp_diagnostics branch

- changes are only in view/qml, no code changes
- adds `PageSettingsModbusTcp.qml` and subpages to `PageSettings.qml`
- gui is functional, tested with demo mode and on a client’s machine
- rebase yielded merge conflict: resolved by removing `Modbus/TCP` menu entry from `PageSettingsServices.qml` (moved to `PageSettingsModbusTcp.qml`)
- tested, working in conjunction with the `WIP_qitems_and_diagnostics_service` branch of `dbus_modbustcp`, see below

#### dbus_modbustcp - WIP_qitems_and_diagnostics_service branch

- many commits, many changes, in many files
- changes seem reasonable, but I can’t pretend I understand 100% of them
- changes could be rebased without conflicts
- compiles without errors and warnings
- tested on test and a clients machine (ccgx), sending various modbus requests, target replied with the expected values
- continuously polled the machine for more than an hour, memory footprint did not increase => memory leak unlikely
- works in conjunction with the `WIP_modbustcp_diagnostics` gui, see above
- the branch adds some unit tests (`/test/main.cpp`): those tests won’t readily run on a target. needs `libQtTestE.so` which can be installed using `opkg install libqtteste4`
unit tests were run locally on x86_64, all of them passed.
- the branch adds some integration tests with `modbustcp_tb.py`. those need *a vebus device [..] and a BMV to be connected to the CCGX* all tests passed, except `test_6`
(because of missing BMV, I do not have access to a system with a BMV)

**Comment by mpvader** [comment]
hey @3dGrabber, I'm looking for your patches in the [gui branch](https://github.com/victronenergy/gui/commits/WIP_modbustcp_diagnostics), but can't find any?

**Comment by mpvader** [comment]
Listed on the v2.40 todo, for Izak.
