### ISSUE TITLE
When using an ET112 meter for a PV-inverter it can only be used on L1

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#288]
For the ET112 meter we only publish values on /Ac/L1 because it is a single-phase meter. There is no way to adjust this. This means that when an ET112 is used to measure production of a PV-inverter, it can only be used for PV-inverters on L1. Ideally it should be possible to set a different phase for PV-inverters only, as it likely makes no sense for other applications.

**Comment by mpvader** [comment]
I'm closing this, there are plenty other things todo. It will come back automatically if important.

**Comment by mpvader** [comment]
ps; customers can buy a three phase meter if they really want this.

**Comment by vincentwolsink** [comment]
I am actually running into this. My PV is single phase, but located on L3 because of self-consumption and net voltages being lower on L3. As a result VRM dashboard adds my solar production to the load on L1. I didn't notice any other side effects yet, besides the display error.

I am looking into https://github.com/victronenergy/dbus-cgwacs to open a PR, but my C++ isn't great. If I manage to produce something, would you be open to merging it? Or would I be wasting my time? :)
