### ISSUE TITLE
mqtt-rpc: check of Lynx Ion+Shunt & Lynx BMS can be unblocked

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#298]
Continued from #282. Before unlocking remote firmware update for these products, we need to know for sure that customers can't hurt themselves / their system.

### Is it wise to update a BMS remotely?
What happens if you update them remotely: do they switch the system off? And what happens with the main contactor? And allow-to-charge and allow-to-discharge outputs? Etc.

And there are some specific issues.

### Lynx Ion BMS series
Problem: Lynx Ion BMS: multiple models. one binary. But they do have different productids. And the issue is that the bootloader only accepts a binary that has a generic productid inside. the code that checks if the productid of the file being sent is valid, is not masking during its check. So, sending a file manually is possible (send the file with the generic productid). But using the firmware library is not possible: the generic file is listed under that generic productid, and therefor not matched.

Solution: Map the specific id to the generic id before doing the firmware library lookup. This would allow us to still offer the update through the firmware library for these products. No need for a blacklist it seems (in this case).

Product id 0xA390-0xA39F have been reserved for the Lynx Ion BMS, where 0xA390 is the generic id. Right now only 0xA391-0xA394 have been assigned to existing products. To be decided if it is fine to map the complete range to the generic id or only the ones that are used?

0xA390: Lynx Ion BMS Generic
0xA391: Lynx Ion BMS 150A
0xA392: Lynx Ion BMS 400A
0xA393: Lynx Ion BMS 600A
0xA394: Lynx Ion BMS 1000A

### Lynx Ion + Shunt 350A and 600A models
0xA130 - Lynx Ion + Shunt. 

### Lynx Ion
Too old product to spend time on. It will remain blacklisted.

0x0142 - Lynx Ion

**Comment by mpvader** [comment]
Answer developers: Main contactor will open, ATC, ATD will disable. Aux power output will stay active during the update, after update is finished it will switch off. Device will reboot automatically and everything will become active again.

Lynx Ion plus Shunt same story, Lynx Ion 350 can only be updated by vup if external can-bus power supply is present and will stay active during contactor opening.

**Comment by mauritsvdvijgh** [comment]
> Lynx Ion 350 can only be updated by vup if external can-bus power supply is present and will stay active during contactor opening.

Is this relevant for (vrm-)mqtt-rpc or will vup return an error code if this is the case?

**Comment by mpvader** [comment]
Yes its relevant. For now just forget about this. Too complicated to fix, at least before my holiday.

**Comment by mpvader** [comment]
As discussed on Slack, next @mauritsvdvijgh will change the code to map these ids:

0xA391: Lynx Ion BMS 150A
0xA392: Lynx Ion BMS 400A
0xA393: Lynx Ion BMS 600A
0xA394: Lynx Ion BMS 1000A

To this one:
0xA390: Lynx Ion BMS Generic

Before doing the firmware library lookup. And then remove blacklisting them.

The other products will remain blacklisted.

**Comment by mpvader** [comment]
Blacklisting has been removed fro 0xA391 to 0xA394 per just now. So manually selecting a file and remote updating those products works.

[Customer manual](https://www.victronenergy.com/live/vrm_portal:remote-firmware-update) is being updated now to include details on what happens during the update (main contactor opens, etc).

Next week the generic id map will be put in place, making the firmware library work for these products, and then this issue can be closed.

**Comment by wilcop85** [comment]
What happens when a update fails? Is is possible to start the update again remotely?

I noticed that sometime's a VUP update fails. When the firmware transfer started, the Lynx Ion BMS is not responding on a received package what results that the Lynx Ion BMS will give timeout error. As we speak i am working on this bug but its hard to trace/reproduce. First impression is that because of other CAN-bus activity(another Lynx Ion BMS) the Lynx Ion BMS can not handle this bulk of data.

Line:5719, message number: 5704
[VupUpdateTraceError8400.txt](https://github.com/victronenergy/venus/files/2419458/VupUpdateTraceError8400.txt)

**Comment by mpvader** [comment]
> What happens when a update fails? Is is possible to start the update again remotely?

Normally yes. But please test.

**Comment by wilcop85** [comment]
Tested, updated failed first time. Started update again and succeed. Detail, this has to be done within 5 minutes else the Lynx Ion BMS will go to sleep mode and a push on the start button is required.

Mention bug above:
Lynx Ion BMS is checking in main loop for new CAN-messages. This main loop time somehow is more then 0.5ms what results in missing a FP. I have noticed that during the updated process also PGN ACL request are passing by, this could cause the main loop delay.

**Comment by mpvader** [comment]
> retry tests

Thanks. I've added a note to the manual: `In case the update fails, it can be retried; just like all other products. But in case of the Lynx BMS, this has to be done within 5 minutes. Otherwise it will will go to sleep mode and a push on the start button is required.`

> bug

I understand what you write, sort of :-), but what does it mean? That you are closer to fixing the bug?

**Comment by wilcop85** [comment]
I have rebuild the compleet VUP bootloader app, this was stil on my todo list. Also because we want to implement the BT bootloader in this code.

With the rebuild code I cannot reproduce the fault anymore, the code is compiled more efficient. To be sure I added an extra message router update in the main, this is what already solved the problem in the "old" code.

**Comment by martinbosma** [comment]
@mauritsvdvijgh It looks like the vup header is wrongly parsed.

The vup header for version v1.13 looks like this:
`66 99 14 00 90 A3 00 00 FF 13 01 00 00 00 00 00`

Byte 8-11 contain the firmware version. In this case the version is `0x000113FF`, which can be written as v1.13, since the LSB is set to `0xFF` (release). Note that this is a 24-bit version.
Also, the decimal representation 70655 is bigger than 70143 (`0x0111FF`).

I remember that there was a previous issue regarding the details of parsing firmware files and 16-/24-bit firmware version support, but I can't find it.

**Comment by mauritsvdvijgh** [comment]
@martinbosma Then I believe the problem is in the firmware library.

Request for product id `"A390", decimal: 41872`

https://eorder.victronenergy.com/preprogramming_api/v1/firmware-info/41872

returns:
```
{
    "firmware_version": "275"
}
```

**Comment by mpvader** [comment]
Yes I’ve sent an email about this to mindaugas just now.

**Comment by martinbosma** [comment]
@mauritsvdvijgh Mindaugas has made a fix for this and updated the records. So, it should work now

**Comment by mauritsvdvijgh** [comment]
Enabled the product mapping again and verified that it works.

```
        "product_id_mapping": {
            "A391": "A390",
            "A392": "A390",
            "A393": "A390",
            "A394": "A390",
        }
```

**Comment by mpvader** [comment]
Hoera, closed!
