### ISSUE TITLE
Scheduled charging doesn't stop

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#318]
Easy to replicate / https://vrm.victronenergy.com/installation/1675/dashboard

Affects Scheduled charging: must be resolved before v2.20 release.

Hello Matthijs,

I have found a bug and can replicate it.

I changed the setting for my SC, smaller time frame but to 95% SOC, this left SC on outside the time frame of 30 minutes. I had to switch the SC off to get the multi to stop charging. When i reset the SC it went straight back to charging from the grid.

Best Regards
Andre

**Comment by izak** [comment]
I could not reproduce it on my system. Then I called Andre and tried it on his system, and also could not reproduce it. In his own words, unless he turns off the schedule, it charges "in the middle of the morning". This is what the schedule looks like:

![selection_208](https://user-images.githubusercontent.com/851549/44344040-e7bcf880-a48f-11e8-90fc-52a2d7f0bcb9.png)

That is supposed to charge in the middle of the morning (from 5AM to 11AM). Could it be that he thought the second item is an end time rather than a duration? It's an easy mistake to make and one that looks likely. I will call him again later, he is driving at the moment.
