### ISSUE TITLE
Cant get usb-can-analyzer working

### ISSUE THREAD

**Issue by muzzaau008** [victronenergy/venus#495]
Hi, I bought a usb-can-analyzer exactly like this: https://www.seeedstudio.com/USB-CAN-Analyzer-p-2888.html

I followed the instructions for SLCAN device setup, but it doesn't seem to work. It might be a driver issue, but I can't seem to get one to install. I tried the one from here:  https://github.com/SeeedDocument/USB-CAN-Analyzer/tree/master/res/Driver but the linux version in this image seems to be missing things like apt-get and other things so I couldn't install other things to try to get it to work.

 I'm trying to connect to a Batrium BMS. See here: https://support.batrium.com/article/110-how-to-control-victron-ccgx-with-watchmon

I already have a genuine Victron CCGX and it works fine with the batrium bms. I'm just trying to get a raspberry pi version working the same way. I have the MK3 and it works on the pi and recognises my Victron Multigrid.

**Comment by jhofstee** [comment]
This sound like a request for help, instead of an issue. Please ask for help at victron-dev-venus@googlegroups.com or in the Victron Modification Space on https://community.victronenergy.com. Please note that the rpi is supported by the community.

apt-get is not missing, it simply irrelevant since Venus is not Debian based.
