### ISSUE TITLE
AC input configuration does not allow setting generator and shore power

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#638]
AC input configuration is still broken.
After reboot of the Venus device "Generator" and "Shore power" can not be selected.

**Comment by izak** [comment]
Found it. dbusdeltas.py in vrmlogger tracks the AcIput settings, and ends up setting the maximum to 1. 

This has been the case since August 2015, but because the GUI used to (re)add this setting, and the GUI always started a bit later than vrmlogger, it always ended up correct by the end of it.

Recently this setting was removed from the GUI, and is now added/maintained by mk2-dbus. The timing is now different, and vrmlogger wins the race.

Fix is to to not use SettingsDevice in dbusdeltas in vrmlogger. Track it in the usual manner using a DbusMonitor.
