### ISSUE TITLE
False firmware version warning for MPPT RS

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#655]
Still awaiting full details, but as the title says: warning when there should not be one.

**Comment by rvanzundert** [comment]
Enabling DVCC on a MPPT charger gives "GX Error #48 - DVCC with incompatible firmware", in case the MPPT firmware version is below v1.02.
The error is valid for the VE.CAN MPPT chargers. But since the MPPT RS units currently have a lower firmware version the error does not apply as the required functionality is present and working.
Solutions:
- extend the check to look for specific models that have this issue
- increase the MPPT firmware version above v1.02 (will happen anyway)
