### ISSUE TITLE
Check new openocd version works ok wrt cerbo programming

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#666]
Used openocd version was increased in v2.60~30

**Comment by jhofstee** [comment]
Installing firmware...
Open On-Chip Debugger 0.10.0+dev-00414-gcdf1e826e-dirty (2020-07-01-08:44)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
SysfsGPIO num: swdio = 269
SysfsGPIO num: srst = 270
SysfsGPIO num: swclk = 271
none separate
adapter speed: 400 kHz
cortex_m reset_config sysresetreq
srst_only separate srst_gates_jtag srst_open_drain connect_deassert_srst
adapter_nsrst_delay: 100
adapter_nsrst_assert_width: 100
Info : SysfsGPIO JTAG/SWD bitbang driver
Info : SWD only mode enabled (specify tck, tms, tdi and tdo gpios to add JTAG mode)
Info : This adapter doesn't support configurable speed
Info : SWD DPIDR 0x0bc11477
Info : at91samc21g18.cpu: hardware has 4 breakpoints, 2 watchpoints
Error: couldn't bind gdb to socket on port 3333: Cannot assign requested address
    TargetName         Type       Endian TapName            State
--  ------------------ ---------- ------ ------------------ ------------
 0* at91samc21g18.cpu  cortex_m   little at91samc21g18.cpu  running
Info : SWD DPIDR 0x0bc11477
target halted due to debug-request, current mode: Thread
xPSR: 0x61000000 pc: 0x000031d4 psp: 0x20001400
** Programming Started **
auto erase enabled
Info : SAMD MCU: SAMC21G18A (256KB Flash, 32KB RAM)
wrote 34304 bytes from file /opt/victronenergy/firmware/samc21_slcan_adc.bin in 5.211566s (6.428 KiB/s)
** Programming Finished **
** Verify Started **
verified 34300 bytes in 0.103681s (323.069 KiB/s)
** Verified OK **
** Resetting Target **
Info : SWD DPIDR 0x0bc11477
shutdown command invoked
Installation complete
