### ISSUE TITLE
MFD App - Multi on/off issue

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#697]
https://community.victronenergy.com/answers/57649/view.html

Needs triaging - Reproducible? Regression?

**Comment by martinbosma** [comment]
I'm unable to reproduce with v2.58, v2.60~38 and with the MFD App version from v2.60~37 (since I can't install v2.60~37).
Changing the mode from the MFD App reflects in the GUI and visa versa.

**Comment by mpvader** [comment]
ok I've asked the customer for more info.

**Comment by martinbosma** [comment]
[Update from customer](https://community.victronenergy.com/questions/57252/venus-os-v26037-available-for-testing.html?childToView=59352#comment-59352); same issue with v2.60~38. He posted a screenshot (below) of the boat & motorhome overview, which I didn't test before.

![image](https://user-images.githubusercontent.com/6614648/90727149-18c0a580-e2c3-11ea-9803-83b86ed5fa84.png)

However, even with the overview it is working perfectly when I tested it (on a real multi). So the GUI, overview and MFD app are updated accordingly when changing the multi to on/off/charger only. 

In above screenshot the AC loads are 0W, while in my case this goes to `---` shortly after the multi switches to Off. Perhaps because he has a different setup than I have?

**Comment by vejpasop** [comment]
@martinbosma I can only get the GUI in this state through the Remote console by clicking on the AC-Mode and cycle to ON.
If then I switch to the MFD, in an other tab of my browser, and switch the Multi OFF. The AC-Mode control remaines ON,

The pencil icon in the AC mode field is visible in this case. (It is also visible in the image from the customer)
![image](https://user-images.githubusercontent.com/10847324/90767742-f5f7b680-e2ed-11ea-83e3-fd8afe4f02a0.png)

**Comment by martinbosma** [comment]
@vejpasop Yes, you are right! It looks like the AC Mode is not updated when in edit mode (pencil icon). 

I verified with dbus-spy that `/Mode` is updated when I change the mode on the MFD app, but the overview is not updating accordingly. It seems to me that this is an issue related to the overview, not the MFD app.
