### ISSUE TITLE
ve.direct firmware version might be reported incorrectly

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#782]
Since ve.direct version v3.56 / Venus version v2.62~9 the firmware version from a corrupt text frame might be reported instead of ignored. This can e.g. trigger a DVCC firmware alarm.

**Comment by mpvader** [comment]
- In v2.60 we had another issue that lead to the same complaint.
- This was fixed in vedirect-interface v3.53 / Venus OS v2.62~1.
- And per vedirect-interface v3.56 / Venus OS v2.62~9 another bug was introduced that has same result: invalid frames are accepted anyway, most visibly leading to intermittent DVCC firmware version warnings Its a different bug: unclear if it now in v2.62 happens more often or less often compared to v2.62.

But, thats anyway irrelevant, the solution is simple; a fix is made and being tested right now; and a new v2.63 build with a fix for this will come today/tomorrow. To be released asp.
