### ISSUE TITLE
systemcalc: visualisation of an ESS system with multi off has issues

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#806]
two issues.

First, the grid meter doesn't show properly anymore:

![image](https://user-images.githubusercontent.com/5200296/112887176-20ef8780-90d3-11eb-8f89-86f45b14a90f.png)

while there is still data from it:

![image](https://user-images.githubusercontent.com/5200296/112887228-306ed080-90d3-11eb-8011-c01a6cc7e58f.png)

And a little bit later, when the Multi is switched off, it shows this, which is also wrong:

![image](https://user-images.githubusercontent.com/5200296/112888155-4e890080-90d4-11eb-9e04-9f18acc4cdac.png)

most likely what above picture should do is: (a) show those loads connected directly to AC in, (b) still show critical loads, like two pictures up, (c) still show the ac input

**Comment by mpvader** [comment]
also the VRM looks strange. In a slightly different way though. see screenshot below. And note how left and right are different.

Probably step 1 is to fix dbus-systemcalc to show the info in the proper way, issue is probably that it no longer sees an ESS Assistant.

And then step 2 is to get gui and vrm to use the data properly, if they don't already do that.


![image](https://user-images.githubusercontent.com/5200296/112890762-8cd3ef00-90d7-11eb-9589-63b0c5a3e365.png)

**Comment by izak** [comment]
The reason why the grid meter value is not used when the Multi is off, is because the GUI decides which value to show in that box based on the active AC input, and when the Multi is off it doesn't know. So while the grid value is there, it doesn't know whether it can use it. This logic is [in the GUI][1].

[1]: https://github.com/victronenergy/gui/blob/30372937736226f045aacfadfefb88f00c0280cf/qml/HubData.qml#L26

**Comment by izak** [comment]
Discussion of implementation to date.

1. Systemcalc publishes three new values corresponding to the active AC input. Therefore the GUI no longer needs its own logic and can simply use these values from systemcalc.
2. Systemcalc can make an intelligent decision based on the availability of a grid or genset service, and publish suitable information even when the Multi is off.
3. Fix the hubtype indication in systemcalc, so that the GUI doesn't change to a different overview (losing the Critical Loads block). This also fixes another irritation: Switching the Multi off causes the Tiles view to show "Hub-1", which is obviously wrong.

**Comment by izak** [comment]
Fixed as of Venus v2.80~10.
