### ISSUE TITLE
v2.90 Dyness battery charging issue

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#943]
Report is the answers here: https://community.victronenergy.com/questions/133780/venus-os-v2905-available-for-testing.html

**Comment by izak** [comment]
So it turns out Dyness has more than one kind of battery.

There are the Pylontech "clones", which sends PN in the 0x359 CANID and is historically incorrectly detected as a Pylontech.

But there also appears to be a 16-cell model, which is installed at this site. Charge voltage is 55.5V, so this must be a 16-cell battery, and 0x359 does not have the classic Pylontech indicator, so this battery would have identified as "Generic" before Venus 2.90. 

From googling, there is:

* Dyness BX51100, a 16-cell abttery
* Dyness B4850, a 15-cell battery
* Others?

The reason for the problem in the above report, is that we now treat all Dyness batteries as if they are 15-cell batteries, and in the case of this site, that means the quirk that caps the charge voltage at 52.4V is activated on a 16-cell battery, causing charging to stop.

So the fix is to correctly activate the quirk only for the 15-cell battery, and I have not yet come up with a plan for that.
